# Generated by Django 5.1.3 on 2024-11-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('first_name', models.CharField(help_text='Введите фамилию', max_length=100, verbose_name='Фамилия')),
                ('name', models.CharField(help_text='Введите имя', max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, help_text='Введите отчество', max_length=100, null=True, verbose_name='Отчество')),
                ('comments', models.TextField(blank=True, help_text='Введите комментарий', null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ('name', 'first_name'),
            },
        ),
    ]
